#!/bin/sh

# cache directory
cachedir=/tmp/wsl-image-preview

# transparent image for regular terminal use
blankSrc="./blank.png"
blank="/mnt/c/Users/mushf/Downloads/blank.png"
blankW="C:\/Users\/mushf\/Downloads\/blank.png"

# finished image file path
out="C:\/Users\/mushf\/Downloads\/pic.png"

# path to terminal settings
wrc=/mnt/c/Users/mushf/AppData/Local/Packages/Microsoft.WindowsTerminal_*/LocalState/settings.json

# program to view text files with
txt_viewer="bat --color always"

# variables to be automated later
screen_width=1920
screen_height=1200

convertWindowsPath() {
	pth="$(echo $1 | sed 's/\/mnt\/\(\w\)/\U\1:/g; s/\//\\/g')"
	echo $pth
}

prepare_image () {
	# clear the screen first
	clear_terminal_background

	# get full path of image
	src=$(realpath "$1")

	# create new filename to get rid of spaces
	src2=$(echo $(basename "$1") | sed 's/ /-/g')

	# path to output final preview image to
	dst="$cachedir/$src2"

	# cache image without spaces in filename
	cp "$src" "$dst"

	# get image sizes
	w=$(identify -format %w "$src")
	h=$(identify -format %h "$src")

	# resize image
	factor=$(echo "$screen_width / $w * 100 / 3" | bc -l)%
	convert "$src" -resize $factor $dst

	# update image sizes
	w=$(identify -format %w $dst)
	h=$(identify -format %h $dst)

	# modify sizes
	new_w=$(($w * 2))
	new_h=$(($h * 2))

	# add padding around image and save to new dst
	mogrify -background transparent -gravity west -extent "$new_w"x"$new_h" $dst

	# move to windows file system
	cp $img $out

	# change terminal background
	change_terminal_background $out
}

change_terminal_background () {
	# the background image to set
	img=$1

	# check whether image has been passed in
	if [ $img = "" ]; then
		echo "Please specify background image in change_terminal_background()"
		exit 1
	fi

	# form sed regular expression to replace backgroundImage in terminal settings
	sedregex="0,/backgroundImage\"/s/\(backgroundImage\"\s*:\s*\"\).*\(\"\)/\1$img\2/"

	# perform replacement
	sed -i "$sedregex" $wrc
}

clear_terminal_background () {
	cp $blankSrc $blank
	change_terminal_background $blankW
}

# Init

# get extension of param
ext="${1##*.}"

# if clear is passed in, clear the background
if [ "$1" = "clear" ]; then
	clear_terminal_background

# if not image, show file output
elif [ $ext != "jpg" ] && [ $ext != "jpeg" ] && [ $ext != "png" ] && [ $ext != "gif" ]; then
	clear_terminal_background
	$txt_viewer "$1"

# otherwise show the image
else
	prepare_image "$1"
fi

