#!/bin/sh

# cache directory
# cachedir=/tmp/wsl-image-preview
# cachedir=$HOME/projects/win-term-image-preview/cache
cachedir=~/downloads

# finished image file path
out="~/downloads/pic.png"

resize_image() {
	# get terminal window width and height
	win_dims=$(powershell.exe ./getWindowDims.ps1)
	win_width=$(echo $win_dims | cut -d\  -f 1)
	win_height=$(echo $win_dims | cut -d\  -f 2)

	# get extension of image
	# NOTE: the following will not work with gifs
	ext="${1##*.}"
	# get filename without extension
	dst=$(basename "$1" .$ext)
	# remove spaces and append png
	dst=$(echo $dst | sed 's/ /-/g').png
	# path to output final preview image to
	dst=$cachedir/$dst

	# get image sizes in pixels
	w=$(identify -format %w "$1")
	h=$(identify -format %h "$1")

	# calculate factor to resize image by
	factor=$(echo "$win_width / $w * 100 / 3" | bc -l)%
	# ImageMagick provides 3 options to resize images:
	#   - resize factor => fast
	#   - scale  factor => faster
	#   - sample factor => fastest
	convert "$1" -scale $factor $dst
}

prepare_image () {
	# update image sizes
	w=$(identify -format %w $dst)
	h=$(identify -format %h $dst)

	# modify sizes
	new_w=$(($w * 2))
	new_h=$(($h * 2))

	# add padding around image and save to new dst
	mogrify -background transparent -gravity west -extent "$new_w"x"$new_h" $dst

	# convert out filepath to linux filepath
	out2=$(windows_2_linux $out)
	echo "out2: $out2"

	# move to windows file system
	cp $dst $out2

	# # change terminal background
	change_terminal_background $out
}

init() {
	# get full path of image
	src=$(realpath "$1")

	# resize image
	resize_image $src
}

init $1
